# Generated by Django 6.0.4 on 2026-06-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_voice_character_voice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="character",
            name="name",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="character",
            name="profile",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile",
            field=models.TextField(default="谢谢你的关注!", max_length=100),
        ),
    ]
