# Generated by Django 6.0.4 on 2026-07-23 08:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0009_alter_character_name_alter_character_profile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file_type", models.CharField(max_length=20)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("chunk_count", models.IntegerField(default=0)),
                (
                    "create_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
